### ISSUE TITLE
Error during load_xml

### ISSUE THREAD

**Issue by mjalkio** [CharityNavigator/990_long#3]
Hi, I'm trying to do a test run through the automatic method and am getting this error (from stdout).

```
*** Cloning 990_long.
*** Cloning concordance.
*** Copying concordance to 990_long.
*** Putting concordance into HDFS.
*** Changing directory to 990_long
*** Running load_paths
Production mode is OFF. For test mode, I will retrieve 1000 records per year, starting with the year 2011.
***Process complete.
*** Running load_xml
Traceback (most recent call last):
  File "/home/hadoop/990_long/python/load_xml.py", line 74, in <module>
    input = spark.read.parquet(*args.input) 
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 291, in parquet
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 69, in deco
pyspark.sql.utils.AnalysisException: u'Path does not exist: hdfs://ip-10-0-3-159.us-west-2.compute.internal:8020/user/hadoop/s;'
```

I don't see any errors in stderr. Have you hit this issue before?

**Comment by borenstein** [comment]
Hi @mjalkio, I don't actually recommend using 990_long to analyze the e-file data, as there are better ways to do it. I wrote [this Medium article](https://medium.com/@open990/the-irs-990-e-file-dataset-getting-to-the-chocolatey-center-of-data-deliciousness-90f66097a600) to explain what your options are in 2018. Have a look and let me know your thoughts!

**Comment by mjalkio** [comment]
Thanks @borenstein, I read that article back when you published it and think that it does a fantastic job outlining what has been done and where there are still issues 😄 However, it does say:

> There are a number of tools available to help you get started with 990 data. Charity Navigator got the ball rolling with two parsing libraries: 990 Decoder, which extracts the fields actually used by Charity Navigator, and 990_long, which generates a vast set of key-value pairs.

If you don't recommend 990_long at all, it would be great if you made that more clear. So you suggest IRSx as the best open source tool currently available?

**Comment by borenstein** [comment]
Noted, I'll make a tweak to the article. Yes, IRSx is the best open source
tool currently available.

--
David Bruce Borenstein, PhD
781.710.2789 (m)
https://www.linkedin.com/in/davidborenstein
